import sqlite3

# select distinct perpetrator from attacks where length(perpetrator) > 11;
translate_groups = {
    "Islamistmilitants"                                     : "Islamist Militants",
    "Pakistani Taliban or al-Qaeda linked groups"           : "Pakistani Taliban OR al-Qaeda",
    "Al-Qaeda in the Arabian Peninsula"                     : "Al-Qaeda",
    "al-Qaeda in the Arabian Peninsula"                     : "Al-Qaeda",
    'Hamza Mohammed Hasan Matrouk (lone wolf)'              : "Hamza Mohammed Hasan Matrouk, lone wolf",
    "Donetsk People's Republic orArmed Forces of Ukraine"   : "Donetsk People's Republic OR Armed Forces of Ukraine",
    "3 unnamed suspects (lone wolf)"                        : "3 unnamed suspects, lone wolf",
    "Al-Mourabitoun[57]"                                    : "Al-Mourabitoun",
    "ISIL Yemen branch"                                     : "ISIS",
    "ISIL (affiliate)"                                      : "ISIS",
    "16-year-old Palestinianlone wolf"                      : "16 year old Palestinian, lone wolf",
    "Local Islamic insurgency group"                        : "Islamic insurgency",
    "Ansar Bait al-Maqdis (ISIL)"                           : "Ansar Bait al-Maqdis, ISIS",
    "Khaled Koutineh (Lone wolf)"                           : "Khaled Koutineh, lone wolf",
    "Jundallah, ISIL, Tehrik-i-Taliban Pakistan"            : "Jundallah, ISIS, Tehrik-i-Taliban Pakistan",
    "Omran Abu Dheim (lone wolf)"                           : "Omran Abu Dheim, lone wolf",
    "Islamic State"                                         : "ISIS",
    "Muhammad Abdulazeez(lone wolf)"                        : "Muhammad Abdulazeez, lone wolf",
    "Kurdistan Workers' Party(PKK)"                         : "PKK",
    "Raid Mohammed Badwan (lone wolf)"                      : "Raid Mohammed Badwan, lone wolf",
    "Islamic Stateaffiliate[45]"                            : "ISIS",
    "Palestinian (lone wolf)"                               : "Palestinian, lone wolf",
    "Mahmoud Nasim Yousef Gumhouriyya (lone wolf)"          : "Mahmoud Nasim Yousef Gumhouriyya, lone wolf",
    "Ahmad Kamal Rafik (lone wolf)"                         : "Ahmad Kamal Rafik, lone wolf",
    "Lashkar-e-Jhangvi"                                     : "Lashkar-e-Jhangvi",
    "Abu-Amsha al-Atrash (Palestinian Islamic Jihad)"       : "Abu-Amsha al-Atrash",
    "Ayoub El Kahzani[71]"                                  : "Ayoub El Kahzani",
    "Mahmoud Ata Muammar (lone wolf)"                       : "Mahmoud Ata Muammar, lone wolf",
    "Ansar Bait al-Maqdis(Islamic State)"                   : "Ansar Bait al-Maqdis",
    "Abed Mohamed Abed Rabu Dawiat and his gang"            : "Abed Mohamed Abed Rabu Dawiat",
    "Taliban orHaqqani network"                             : "Taliban, Haqqani network",
    "Hamas affiliated cell"                                 : "Hamas affiliated cell",
    "Farhad Khalil Mohammad Jabar (lone wolf)"              : "Farhad Khalil Mohammad Jabar, lone wolf",
    "Fadi Aloon (lone wolf)"                                : "Fadi Aloon, lone wolf",
    "Amjad al Jundi (ofHamas)"                              : "Amjad al Jundi",
    "Tamer Yunis Ahmed (Lone wolf)"                         : "Tamer Yunis Ahmed, lone wolf",
    "Subhi Ibrahim Mohammed Abu Khalifa (Lone wolf)"        : "Subhi Ibrahim Mohammed Abu Khalifa, lone wolf",
    "Tair Abu Gazala (Lone wolf)"                           : "Tair Abu Gazala, lone wolf",
    "Palestinian Lone wolf"                                 : "Palestinian, lone wolf",
    "Tarak Yahya (Lone wolf)"                               : "Tarak Yahya, lone wolf",
    "Jewish teen (Lone wolf)"                               : "Jewish teen, lone wolf",
    "Palestinian lone wolf"                                 : "Palestinian, lone wolf",
    "Palestinian lone wolf"                                 : "Palestinian, lone wolf",
    "Ishak Badran (lone wolf)"                              : "Ishak Badran, lone wolf",
    "Muhammad Ali (lone wolf)"                              : "Muhammad Ali, lone wolf",
    "Boko Haramsuspected"                                   : "Boko Haram",
    "Baha Aliyan and Bilal Ranem ()"                        : "Baha Aliyan, Bilal Ranem",
    "Alaa Abu Jamal (lone wolf)"                            : "Alaa Abu Jamal, lone wolf",
    "Israeli Jewish lone wolf"                              : "Israeli Jewish, lone wolf",
    "Ahmed Shaaban (23) (lone wolf)"                        : "Ahmed Shaaban, lone wolf",
    "Islamic State or Saudi nationalists"                   : "ISIS",
    "Muhand al-Okabi (lone wolf)"                           : "Muhand al-Okabi, lone wolf",
    "Anton Lundin Pettersson"                               : "Anton Lundin Pettersson",
    "Wilayah Sayna(Islamic State)"                          : "ISIS",
    "Ansar al-Islam Ansarullah Bangla Team"                 : "Ansarullah Bangla Team",
    "Palestinianlone wolf"                                  : "Palestinian, lone wolf",
    "Sulemain Shaheen lone wolf"                            : "Sulemain Shaheen, lone wolf",
    "Wilayah Sayna (Islamic State)"                         : "ISIS",
    "Baraa Issa (Al-Aqsa Martyrs' Brigades or lone wolf)"   : "Baraa Issa, lone wolf",
    "Al-Mourabitoun"                                        : "Al-Mourabitoun",
    "Islamic State[197]"                                    : "ISIS",
    "Bassm Salah (Palestinianlone wolf)"                    : "Bassm Salah, lone wolf",
    "Mazen Aribah (lone wolf)"                              : "Mazen Aribah, lone wolf",
    "Abed al-Rahman al-Barghouthi (lone wolf)"              : "Abed al-Rahman al-Barghouthi, lone wolf",
    "Muhyadin Mire"                                         : "Muhyadin Mire",
    "Wilayat Sayna(Islamic State)"                          : "ISIS",
    "Abd al-Rahman (lone wolf)"                             : "Abd al-Rahman, lone wolf",
    "unknownPalestinians"                                   : "Palestinians",
    "Abed Almohsin Hassoneh (lone wolf)"                    : "Abed Almohsin Hassoneh, lone wolf",
    "Mahmoud Faisal Basharat (lone wolf)"                   : "Mahmoud Faisal Basharat, lone wolf",
    "Tarek Belgacem (Islamic State-inspired)"               : "ISIS",
    "Turkish youth (Islamic State-inspired)"                : "Turkish boy",
    "Tehrik-i-Taliban Pakistan orJaishul Islam"             : "Tehrik-i-Taliban Pakistan",
    "Islamist extremists suspected"                         : "Islamist extremist",
    "Communist Party of India (Maoist)"                     : "Maoist",
    "al-Qaeda in the Islamic Maghreb"                       : "al-Qaeda",
    "Communist Party of India(Maoist)"                      : "Maoist",
    "Tehreek-e-Taliban Pakistan"                            : "Tehreek-e-Taliban",
    "Syrian rebelgroup"                                     : "Syrian rebel group",
    "Tehreek-i-Taliban Pakistan"                            : "Tehreek-i-Taliban",
    "Kalzar al-Uweiwi"                                      : "Kalzar al-Uweiwi",
    "IS linked Wilayat Sayna"                               : "ISIS",
    "Lashkar-e-Taiba"                                       : "Lashkar-e-Taiba",
    "Gultchekhra Bobokoulova"                               : "Gultchekhra Bobokoulova",
    "Allied Democratic Forces"                              : "Allied Democratic Forces",
    "Carlos Peralta (lone wolf)"                            : "Carlos Peralta, lone wolf",
    "Bashar Massalha"                                       : "Bashar Massalha",
    "Mai-Mai withFDLR"                                      : "Mai-Mai",
    "Palestinianlone wolfs"                                 : "Palestinian, lone wolf",
    "Farouq Brigades andAhrar al-Sham"                      : "Farouq Brigades, Ahrar al-Sham",
    "Al-Shabaabsuspected"                                   : "Al-Shabaab",
    "Al-shabaabsuspected"                                   : "Al-shabaab",
    "Al-Qaeda in the Indian Subcontinent"                   : "Al-Qaeda",
    "Talibansuspected"                                      : "Taliban",
    "Wilayat Saynasuspected"                                : "Wilayat Sayna",
    "TBD"                                                   : "Unknown",
    "Unknown"                                               : "Unknown terrorist",
    ""                                                      : "Uknown terrorist",
}

extended_name_list = {
    "PKK"   : "Kurdistan Workers' Party OR PKK",
    "ISIS"  : "ISIS OR ISIL OR Islamic State"
}

def update():
    conn = sqlite3.connect('attacks.db')
    c = conn.cursor()
    query = 'UPDATE attacks SET perpetrator=? WHERE perpetrator=?;'
    for occurrence, correction in translate_groups.items():
        values = (correction, occurrence)
        c.execute(query, values)
    conn.commit()
    conn.close()
